[package]
name = "memory-palace"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = {version = "4.2", features = ["derive"]}
iso8601-duration = {version = "0.2.0", features = ["chrono"]}
rand = "0.8.5"
serde = {version = "1.0", features = ["derive"]}
static_init = "1.0.3"
toml = "0.7"
